site_name: Ikukantai - 行く艦隊
site_url: https://ikukantai.bonavadeur.io.vn
repo_url: https://github.com/bonavadeur/ikukantai
theme:
  name: material
  logo: assets/images/logo.ico
  favicon: assets/images/logo.ico
  palette:
    scheme: default
    primary: custom
    accent: red
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - search.suggest
  - search.highlight
extra_css:
- stylesheets/extra.css
plugins:
- search
- i18n:
    docs_structure: folder
    languages:
    - locale: en
      default: true
      name: English
      build: true
      reconfigure_search: true
      nav:
      - Home:
        - Introduction: index.md
        - Architecture: architecture.md
        - Features:
          - Overview: features/index.md
          - Scheduler: features/scheduler.md
          - Load Balancer: features/load-balancer.md
          - Queue Modifier: features/queue-modifier.md
        - How to start?: how-to-start.md
      - Installation: installation.md
      - Miporin:
        - Overview: miporin/index.md
        - Architecture: miporin/architecture.md
        - Installation: miporin/installation.md
        - Development: miporin/development.md
        - Learn: miporin/learn.md
        - References: miporin/references.md
      - Katyusha:
        - Overview: katyusha/index.md
        - Architecture: katyusha/architecture.md
        - Installation: katyusha/installation.md
        - Development: katyusha/development.md
        - Learn: katyusha/learn.md
        - References: katyusha/references.md
      - Nonna:
        - Overview: nonna/index.md
        - Architecture: nonna/architecture.md
        - Installation: nonna/installation.md
        - Development: nonna/development.md
        - Learn: nonna/learn.md
        - References: nonna/references.md
      - About: about.md
    - locale: vi
      name: Tiếng Việt
      build: true
      reconfigure_search: true
      nav:
      - Trang chủ: index.md
    - locale: ja
      name: 日本語
      build: true
      reconfigure_search: true
      nav:
      - ホーム: index.md
